### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by ghost** [rcook/elkulator#1]
Hi,
I can't build elkulator : 

[ 91%] Linking C executable elkulator
CMakeFiles/elkulator-objs.dir/src/palfilt.c.o : Dans la fonction « palfilter » :
palfilt.c:(.text+0x42e) : référence indéfinie vers « iir »
palfilt.c:(.text+0x458) : référence indéfinie vers « firry »
palfilt.c:(.text+0x465) : référence indéfinie vers « firby »
palfilt.c:(.text+0x621) : référence indéfinie vers « iir »
palfilt.c:(.text+0x64b) : référence indéfinie vers « firry »
palfilt.c:(.text+0x658) : référence indéfinie vers « firby »
collect2: error: ld returned 1 exit status
CMakeFiles/elkulator.dir/build.make:154 : la recette pour la cible « elkulator » a échouée
make[2]: *** [elkulator] Erreur 1
CMakeFiles/Makefile2:67 : la recette pour la cible « CMakeFiles/elkulator.dir/all » a échouée
make[1]: *** [CMakeFiles/elkulator.dir/all] Erreur 2
Makefile:138 : la recette pour la cible « all » a échouée
make: *** [all] Erreur 2

**Comment by rcook** [comment]
Most likely you are using an incompatible version of a third-party dependency. Unfortunately, I don't have time to investigate this.

**Comment by gripped** [comment]
For the benefit of anyone else who come across this:

Add static in front of inline on lines 27,41 & 54 of elkulator/src/palfilt.c

you will also need the roms from the original linux version
http://elkulator.acornelectron.co.uk/ElkulatorV1.0Linux.tar.gz
or
http://odroidxu.leeharris.me.uk/ElkulatorV1.0Linux.tar.gz

After this I got it running. I am not a programmer so if this causes your computer to attack your cat it's not my fault :)
